base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:
  odom_topic: /rbcar_robot_control/odom
  map_frame: /map

  # Trajectory

  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: False
  max_global_plan_lookahead_dist: 20
  feasibility_check_no_poses: 4

  # Robot

  max_vel_x: 6.5
  max_vel_x_backwards: 1.0
  max_vel_y: 0.0
  max_vel_theta: 0.345
  acc_lim_x: 1.5
  acc_lim_y: 0.0
  acc_lim_theta: 0.2
  min_turning_radius: 6.6
  wheelbase: 2.07
  cmd_angle_instead_rotvel: True # set true in ackermann mode
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    #type: "point"
    #type: "circular"
    #radius: 0.6
    type: "line"
    line_start: [0.0, 0.0]
    line_end: [2.07, 0.0]
    #type: "two_circles"
    #front_offset: 0.2
    #front_radius: 0.2
    #rear_offset: 0.2
    #rear_radius: 0.2
    #type: "polygon"
    #vertices:
     # [[-0.25, -0.51686], [1.82, -0.51686], [1.82, 0.51686], [-0.25, 0.51686]]

  # GoalTolerance

  xy_goal_tolerance: 0.8
  yaw_goal_tolerance: 0.4
  free_goal_vel: False

  # Obstacles

  min_obstacle_dist: 0.9
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 6.0
  obstacle_poses_affected: 30
  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  #costmap_converter_plugin: "" # deactivate plugin
  costmap_converter_spin_thread: True
  costmap_converter_rate: 10
  # costmap_converter/CostmapToLinesDBSRANSAC:
  #    cluster_max_distance: 0.4

  # Optimization 
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.01
  weight_max_vel_x: 2
  weight_max_vel_y: 1
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_y: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 10
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10 # not in use yet
  selection_alternative_time_cost: False

  # Homotopy Class Planner

  enable_homotopy_class_planning: False
  enable_multithreading: True
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100.0
  selection_prefer_initial_plan: 0.95
  selection_viapoint_cost_scale: 1.0
  simple_exploration: False
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
