controller_frequency: 2.0

base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:
  odom_topic: rbcar_robot_control/odom
  map_frame: map

  # Trajectory

  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: True
  max_global_plan_lookahead_dist: 30.0
  feasibility_check_no_poses: 5

  # Robot

  max_vel_x: 6.5
  max_vel_x_backwards: 0.2
  max_vel_y: 0.2
  max_vel_theta: 0.3 # the angular velocity is also bounded by min_turning_radius in case of a carlike robot (r = v / omega)
  acc_lim_x: 0.8
  acc_lim_theta: 0.4

 # ********************** Carlike robot parameters ********************
  min_turning_radius: 0.2        # Min turning radius of the carlike robot (compute value using a model or adjust with rqt_reconfigure manually)
  wheelbase: 1.65                 # Wheelbase of our robot
  cmd_angle_instead_rotvel: True # stage simulator takes the angle instead of the rotvel as input (twist message)
 # ********************************************************************
  footprint_model:
    # type: circular
    # radius: 0.235
    type: polygon
    vertices: [[0.6065,0.6065], [0.6065,0.6368], [1.0917,0.6368], [1.0917,0.4427], [0.94,0.4427], [0.94,0.2459], [1.03,0.2459], [1.03,-0.2459], [0.94,-0.2459], [0.94,-0.4427], [1.0917,-0.4427], [1.0917,-0.6368], [0.6065,-0.6368], [0.6065,-0.6065], [-0.6065,-0.6065], [-0.6065,-0.6368], [-1.0917,-0.6368], [-1.0917,-0.6065], [-1.31,-0.6065], [-1.31,-0.5822], [-1.6133,-0.5822], [-1.6133,0.5822], [-1.31,0.5822], [-1.31,0.6065], [-1.0917,0.6065], [-1.0917,0.6368], [-0.6065,0.6368], [-0.6065,0.6065], [0.6065,0.6065]]
      # - [0.235,0.17]
      # - [0.235,-0.17]
      # - [-0.235,-0.17]
      # - [-0.235,0.17]
    #type: two_circles
    #front_offset: 0.156
    #front_radius: 0.156
    #rear_offset: 0.156
    #rear_radius: 0.156

  # GoalTolerance
    
  xy_goal_tolerance: 0.6
  yaw_goal_tolerance: 0.7
  free_goal_vel: False
    
 # Obstacles
    
  min_obstacle_dist: 0.80 # This value must also include our robot's expansion, since footprint_model is set to "line".
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5

 # Optimization
    
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 5
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 5
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10 # not in use yet

  # Homotopy Class Planner

  enable_homotopy_class_planning: True
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 1.0
  selection_alternative_time_cost: False
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
