robot_base_frame: /base_footprint
#---standard pioneer footprint---
#---(in meters)---
#footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]
footprint: [[0.6065,0.6065], [0.6065,0.6368], [1.0917,0.6368], [1.0917,0.4427], [0.94,0.4427], [0.94,0.2459], [1.03,0.2459], [1.03,-0.2459], [0.94,-0.2459], [0.94,-0.4427], [1.0917,-0.4427], [1.0917,-0.6368], [0.6065,-0.6368], [0.6065,-0.6065], [-0.6065,-0.6065], [-0.6065,-0.6368], [-1.0917,-0.6368], [-1.0917,-0.6065], [-1.31,-0.6065], [-1.31,-0.5822], [-1.6133,-0.5822], [-1.6133,0.5822], [-1.31,0.5822], [-1.31,0.6065], [-1.0917,0.6065], [-1.0917,0.6368], [-0.6065,0.6368], [-0.6065,0.6065], [0.6065,0.6065]]

transform_tolerance: 0.2
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 3.0
 raytrace_range: 3.5
 inflation_radius: 0.2
 track_unknown_space: false
 combination_method: 1
 observation_sources: point_cloud_lidar point_cloud_camera
 point_cloud_lidar: {
   data_type: PointCloud2, 
   topic: velodyne_points, 
   min_obstacle_height: 0.25, 
   max_obstacle_height: 2.5, 
   obstacle_range: 50.0, 
   raytrace_range: 55.0,
   observation_persistence: 0.0,
   marking: true, 
   clearing: true
   }
 point_cloud_camera: {
   data_type: PointCloud2, 
   topic: kinect/depth/points, 
   min_obstacle_height: 0.4, 
   max_obstacle_height: 2.5, 
   obstacle_range: 20.0, 
   raytrace_range: 22.5,
   observation_persistence: 0.0,
   marking: true, 
   clearing: true
   }
#  observation_sources: laser_scan_sensor
#  laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}


inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"