global_frame: /map
static_map: false
rolling_window: true
width: 7.0
height: 7.0

plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}